# Generated by Django 5.0.1 on 2024-01-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpassword', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
